# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: customs.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'customs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcustoms.proto\x12\x07\x63ustoms\"}\n\x14ProductWithInventory\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x12\n\ncompany_id\x18\x06 \x01(\t\"F\n\rInventoryInfo\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\r\n\x05stock\x18\x03 \x01(\x05\")\n\x0fTransactionInfo\x12\x16\n\x0etransaction_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTWITHINVENTORY']._serialized_start=26
  _globals['_PRODUCTWITHINVENTORY']._serialized_end=151
  _globals['_INVENTORYINFO']._serialized_start=153
  _globals['_INVENTORYINFO']._serialized_end=223
  _globals['_TRANSACTIONINFO']._serialized_start=225
  _globals['_TRANSACTIONINFO']._serialized_end=266
# @@protoc_insertion_point(module_scope)
